"""
Django settings for chatbot_project project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
"""
Minimal settings for a single-app demonstration project.
Only the essentials are left enabled.
"""
from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-change-me"  # for demos only

DEBUG = True
ALLOWED_HOSTS = []        # add hosts / 127.0.0.1 in production

# --- Apps -------------------------------------------------------------
INSTALLED_APPS = [
    "django.contrib.staticfiles",   # we only need static files for CSS
    "chat",                         # our chatbot app
    "django.contrib.sessions",      # for storing chat history
]

# --- Middleware (kept minimal) ---------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",  # stores chat history
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",             # enables {% csrf_token %}
]

ROOT_URLCONF = "chatbot_project.urls"
WSGI_APPLICATION = "chatbot_project.wsgi.application"
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],                    # Django will find templates within apps
        "APP_DIRS": True,
        "OPTIONS": {"context_processors": []},
    }
]

# --- Static files -----------------------------------------------------
STATIC_URL = "static/"
STATICFILES_DIRS = []  # static/ directories inside apps are collected automatically

# --- Session storage --------------------------------------------------
# Default cookie-based sessions are fine for a demo
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # ← or 'postgresql', etc.
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
